#!/bin/bash

# Set bash environment error management

set -e
set -u

# Source local functions file

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $script_dir/functions

# Check for root user runtime

check_root

################################################################################

# Source openspace functions file

source_os_functions

################################################################################

os-define_formatting

define_vars

echo

################################################################################

echo "${b}Adding site access to SFTP user...${x}"
echo

choose_local_user

choose_local_site

echo "${b}Adding access to site | ${g}$sel_site${x}${b} | to SFTP user | ${g}$sel_user${x}${b} |...${x}"
echo

sudo -u $sel_user mkdir -p /home/$sel_user/www/$sel_site_name

if ! grep -q "/home/$sel_user/www/$sel_site_name" /etc/fstab
then
    echo "${b}Adding line to fstab...${x}"
    echo
    echo "bindfs#$sel_site /home/$sel_user/www/$sel_site_name fuse force-user=$sel_user,force-group=$sel_user,create-for-user=www-data,create-for-group=www-data,create-with-perms=0770,chgrp-ignore,chown-ignore,chmod-ignore 0 0" >> /etc/fstab
else
    echo "${b}Site already present in fstab...${x}"
    echo
    echo site already added for user to fstab
fi

mount -a &> /dev/null

echo "${b}Finished site access to SFTP user.${x}"
echo
