#!/bin/bash

### openspace bash installer v0.1.0 [https://github.com/openspace42/bash_installer]

################################################################################

### Set bash environment error management

set -e
set -u

### Source local functions file

echo
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. $source_dir/functions

### Source openspace functions file

source_os_functions

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

if [[ "${@#--return-check}" = "$@" ]]
then
        echo "${r}${b}This script must not be run directly.${x}"
	echo
        echo "${b}You should instead run the | ${x}${g}${b}setup${x}${b} | script and it will take care of the installation itself.${x}"
	echo
        echo "${b}Exiting...${x}"
        echo
        exit 1
fi

################################################################################

### Check for any already existing installation

skip_backup=y
os-check_install_version

### All ready for installation

echo "${b}Initiating install...${x}"
echo

################################################################################

install_easyengine

echo "${b}Now installing scripts in | $install_dir/ | ...${x}"
echo

rsync -aAXx $source_dir/ $install_dir/ --include=ee-br-backup --include=ee-br-restore --include=functions --exclude="*"

echo "${b}Finished installing scripts.${x}"
echo

os-set_admin_email

os-setup_backup_restore

describe_setting() {

	echo "${b}Please specify any sites to exclude from your backups.${x}"
	echo
	echo "${b}Type in a comma separated list of websites to exclude.${x}"
	echo
        echo "${b}Example: | example.org, hello.world, site-to.exclude.tld |.${x}"
	echo
        echo "${b}Enter | null | to skip excluding any site.${x}"
	echo

}

os-set_option -o backup_exclude_sites -v n -d y -p backups/local

os-add_cron_job -n $short_name-backup -t "8 4 * * * " -c "bash /root/openspace42/ee-br/ee-br-backup"

################################################################################

### Mark installer as completed successfully

touch $source_dir/install_complete
