#!/bin/bash

################################################################################

### Set bash environment error management

set -e
set -u

### Source local functions file

echo
source_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ "$source_dir" == */tools ]]
then
        source_dir="${source_dir%/tools}"
fi

. $source_dir/functions

### Check for root user runtime

check_root

### Download and source openspace functions file

while getopts ":be" arguments; do
    case $arguments in
        b)	export bleeding_edge_bf="-b"
        echo "Using bleeding-edge bash-functions as per | -b |."
        echo
        ;;
        e)	export bleeding_edge_rc="-e"
        echo "Using bleeding-edge repo code as per | -e |."
        echo
        ;;
        \?)	echo "Invalid option | -$OPTARG | for function | ${FUNCNAME[0]} |."
        echo
        exit
        ;;
    esac
done

OPTIND=1

download_os_functions ${bleeding_edge_bf-}
source_os_functions

### Define formatting

os-define_formatting

### Define variables

define_vars

################################################################################

####################
### Migration extras
####################

### Check for old ee-br named dir and renames it to raptor

if [ -d "/root/openspace42/ee-br" ]
then
  mv "/root/openspace42/ee-br" "/root/openspace42/raptor"
fi

### Check for old ee-sftp dir

if [ -d "/root/openspace42/ee-sftp" ]
then
  rm -r "/root/openspace42/ee-sftp"
fi

### Check for old cron job

if [ -f "/etc/cron.d/ee-br-backup" ]
then
  rm "/etc/cron.d/ee-br-backup"
fi

####################
###### Migration end
####################

### Actually run the installer

os-run_install
