#!/usr/bin/env bash

################################################################################

### Set bash environment error management

set -eu

### Add padding to output

echo

### Determine script execution directory, install directory, and source local functions file

exec_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

exec_dir_trim_2="$( echo ${exec_dir} | cut -f 1,2,3 -d'/')"
exec_dir_trim_3="$( echo ${exec_dir} | cut -f 1,2,3,4 -d'/')"

if [ -f "${exec_dir_trim_2}/functions" ]
then
	exec_dir_root="${exec_dir_trim_2}"
else
	if [ -f "${exec_dir_trim_3}/functions" ]
	then
		exec_dir_root="${exec_dir_trim_3}"
	else
		echo "Functions file not found in any second or third level parent directory of: | $exec_dir |"
		echo
        exit 1
	fi
fi

. "$exec_dir_root/functions"

### Source openspace functions file

source_os_dna

### Define formatting

dna-define_formatting

### Define variables

define_vars

################################################################################

check_root

dna-head_script

dna-read_conf_settings

################################################################################

echo "${b}Adding site access to SFTP user...${x}"
echo

choose_local_user

choose_local_site

echo "${b}Adding access to site | ${g}$sel_site${x}${b} | to SFTP user | ${g}$sel_user${x}${b} |...${x}"
echo

sudo -u $sel_user mkdir -p /home/$sel_user/www/$sel_site_name

if ! grep -q "/home/$sel_user/www/$sel_site_name" /etc/fstab
then
    echo "${b}Adding line to fstab...${x}"
    echo
    echo "bindfs#$sel_site /home/$sel_user/www/$sel_site_name fuse force-user=$sel_user,force-group=$sel_user,create-for-user=www-data,create-for-group=www-data,create-with-perms=0770,chgrp-ignore,chown-ignore,chmod-ignore 0 0" >> /etc/fstab
else
    echo "${b}Site already present in fstab...${x}"
    echo
    echo site already added for user to fstab
fi

mount -a &> /dev/null

echo "${b}Finished site access to SFTP user.${x}"
echo
